### PR TITLE
Add Tiny Freddy Game

### PR DESCRIPTION
**Pull request by SillyArcade**
Five nights at freddys, but small :D
There are also a few changes that make the game easier to play, as well as a little more fresh.

### CODE REVIEW

**Comment by jmtinycircuits** [comment]
Looks like the arcade description is called `arcade_description.txt.txt`. Would you be able to remove the extra .txt?

**Comment by SillyArcade** [comment]
Alright, I believe I changed it, let me know if you see that it's changed.

**Comment by jmtinycircuits** [comment]
Looks like the video file is called `.webm.webm` can you file that too please?

**Comment by SillyArcade** [comment]
I updated it. I dont think there are anymore xyz.a.a files left to change. Thanks for working with me!

**Pull request merged**
