### PR TITLE
Add Silicon8 to arcade

### PR DESCRIPTION
**Pull request by Timendus**
# Silicon8 for Thumby

Silicon8 allows you to run games made for the CHIP-8, SCHIP and XO-CHIP programming languages on your Thumby. It comes bundled with a selection of 15 games, spanning 44 years, to get you started. The Internet has many more compatible games if you feel adventurous 😄

For more information on CHIP-8 and friends, on installing more games and the interpreter's limitations, see: https://github.com/Timendus/thumby-silicon8#readme

* **Author:** [Tim Franssen (Timendus)](https://github.com/Timendus)
* **Version:** v1.0.0
* **License:** GPL-3.0

### CODE REVIEW

**Comment by jmtinycircuits** [comment]
Great to see this here!

I think it is pretty necessary for me to fix https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/issues/23 before merging this.

**Comment by Timendus** [comment]
It sends just fine as far as I know. It's the getting files back from the Thumby after you have installed this that's the issue 😉 Maybe we could just add a warning to the description file for now..?

**Comment by Timendus** [comment]
Any news on this or [the related issue](https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/issues/23) yet?

**Comment by jmtinycircuits** [comment]
I've tried investigating and can't reproduce that issue often. Maybe it isn't entirely related to the number of files. Because of this, I'll merge this now and solve and issues that occur later.

This is one of the coolest projects by the way!

**Comment by jmtinycircuits** [comment]
Looks like my URL list builder crashed, you'll have to give me a bit for it to show up on the arcade.

**Comment by Timendus** [comment]
> This is one of the coolest projects by the way!

Thank you! 🎉😄

**Pull request merged**
