### PR TITLE
Add a game called Burn's Charade

### PR DESCRIPTION
**Pull request by cfleiner**
Hiya! This is a small game to train the player's memory.

The development of this game is completed.

### CODE REVIEW

**Comment by cfleiner** [comment]
*added a second game (Burn's BrickBreaker). A game similiar to brick'd, but with additional features

**Comment by jmtinycircuits** [comment]
Looking good.

When starting the brick game, pressing A to start the game also moves the paddle which makes the ball miss initially. You should check that the A button is released before starting the game.

Let me know if you want to fix that first or just merge.

**Comment by cfleiner** [comment]
Fair enough. I fix that in near time and inform you.

**Comment by cfleiner** [comment]
@jmtinycircuits bugs are fixed. Ready to merge.

**Comment by jmtinycircuits** [comment]
Alright! Looks good to me.

**Pull request merged**
