### PR TITLE
Add Pico Bomb!

### PR DESCRIPTION
**Pull request by disrespectme**
This is my game called Pico Bomb! Based off of a famous Atari 2600 game. The game is complete!

### CODE REVIEW

**Comment by samclane** [comment]
Very cool game! Seemed to work on the official emulator just fine for me.

**Comment by disrespectme** [comment]
I also tested it on the Thumby and it works so I'm just waiting for it to get approved!

**Comment by disrespectme** [comment]
I'm gonna go see you're game!

**Comment by jmtinycircuits** [comment]
Looking good! Maybe I don't understand the game, but I can't avoid the bombs. When the bombs get to the same Y level as the paddle/player it registers a hit no matter where the player is.

**Comment by samclane** [comment]
> Looking good! Maybe I don't understand the game, but I can't avoid the bombs. When the bombs get to the same Y level as the paddle/player it registers a hit no matter where the player is.

I think the "player" is a pool of water, which extinguishes the bombs. The "hit" you're experiencing is a bomb bypassing the pool (and presumably hitting the person behind it, removing 1 hit point).

**Comment by disrespectme** [comment]
> > Looking good! Maybe I don't understand the game, but I can't avoid the bombs. When the bombs get to the same Y level as the paddle/player it registers a hit no matter where the player is.
> 
> I think the "player" is a pool of water, which extinguishes the bombs. The "hit" you're experiencing is a bomb bypassing the pool (and presumably hitting the person behind it, removing 1 hit point).
Correct!!!

**Comment by jmtinycircuits** [comment]
Haha, I get it now. My bad. Merged!

**Pull request merged**
