### PR TITLE
Add Thario Run

### PR DESCRIPTION
**Pull request by jeroenpeters1986**
Hi, here is a plumber inspired running game

### CODE REVIEW

**Comment by jmtinycircuits** [comment]
Would you be able to use a slightly higher resolution video? You can use the zoom function in the emulator.

**Comment by jeroenpeters1986** [comment]
> Would you be able to use a slightly higher resolution video? You can use the zoom function in the emulator.

It has been updated :-)

**Comment by jeroenpeters1986** [comment]
@jmtinycircuits I'm sorry I still had the wrong format. Now I don't, it's the 8x zoom I think. Also, I added some new gamethings like extra enemies, decoration and collecting coins

**Comment by jeroenpeters1986** [comment]
@jmtinycircuits is there something else I am missing? I have seen lots of PRs approved in the meantime, but mine isn’t. If there is anything I can help with, please let me know.

**Comment by jmtinycircuits** [comment]
Sorry for the wait.

Looks good! Thanks!

**Pull request merged**
