### PR TITLE
Add Micro Square Root Calc

### PR DESCRIPTION
**Pull request by BBfiChe**
Hi there, This is a Micro Square root Calculator and for now its just in beta with most of the functionality in it and more functionality other than calculating square root will be added hopefully in the near future. :)

### CODE REVIEW

**Comment by TinyCircuits** [comment]
Could you add a way to exit the game? Right now it looks like it loops forever (at a very quick glance).

It could be as simple as a little exit button that the user clicks to call `thumby.reset()`

**Comment by BBfiChe** [comment]
Yes, I am working on a fix to implement with a exit feature so I will be implementing that soon!
Do I need to implement this to be able to put it on code.thumby.us?
Thanks!

**Comment by BBfiChe** [comment]
I made a new commit to the file!

**Comment by BBfiChe** [comment]
Updated @TinyCircuits! :)

**Comment by BBfiChe** [comment]
@TinyCircuits When you have the chance please get back to me about adding this. Thank you! :)

**Comment by TinyCircuits** [comment]
Looks good, Thanks!

**Pull request merged**
