### PR TITLE
Update Thumby Smash for New API

### PR DESCRIPTION
**Pull request by SandytheLizard**

### CODE REVIEW

**Comment by jmtinycircuits** [comment]
Looking good!

I came across a couple of bugs/QOL changes that would ne nice to have before accepting this.

1. Start menu cursor scroll goes off screen very easily. Simply do not allow the cursor to go further or less than the number of options on the screen.
2. It is hard to tell which damage modifier belongs to the player or AI. Maybe placing them at the top of the screen with some kind of indicator like 'YOU: XXX       AI: XXXX'
3. No way to play again after finishing a match, just says 'win'

**Review by SandytheLizard — COMMENTED** [review]
Fixed the things you suggested

**Review by SandytheLizard — COMMENTED** [review]
This is fixed now

**Comment by jmtinycircuits** [comment]
I found some more bugs.

1. The cursor can go offscreen in the config menu
2. Text in the config menu is not placed well

**Pull request merged**
