### PR TITLE
Bug fix for ThumBird

### PR DESCRIPTION
**Pull request by MrGiraffe24**
Removed debug beep and extra unnecessary code.
I think there might be a problem with this pull request so yeah, just let me know plz.

### CODE REVIEW

**Comment by MrGiraffe24** [comment]
I don't really know how the files are conflicting.
I want it to be 35 not 5 in line: 342-346
and 'Break' at the end just the same

**Comment by MrGiraffe24** [comment]
well I know how they are conflicting, just not why.  By the way there are also non conflicting fixes that are in the code.

**Comment by MrGiraffe24** [comment]
ok I guess I fixed it

**Comment by jmtinycircuits** [comment]
This was fixed in commit 7dd7a00

**Pull request closed without merging**
