### PR TITLE
Add Melody Maker app

### PR DESCRIPTION
**Pull request by FestyWalrus**
This is a little app to make melodies on the Thumby, similar to the Animal Crossing town tune maker.

### CODE REVIEW

**Comment by jmtinycircuits** [comment]
Thanks for the quick fix.

Looks like there is a `MelodyMaker.py` file at `/` and at `/Games/MelodyMaker/`

**Comment by FestyWalrus** [comment]
Thank you for finding that bug! Melody Maker should be ready now.

**Comment by FestyWalrus** [comment]
Oops! I just fixed it.

**Comment by jmtinycircuits** [comment]
Thanks!

Looks good to me.

**Pull request merged**
