### PR TITLE
Added DiscDungeon game

### PR DESCRIPTION
**Pull request by PossiblyAxolotl**
Here's my first Thumby game! It's a top-down arcadey game similar to disc room where you avoid sawblades to get a highscore

### CODE REVIEW

**Comment by PossiblyAxolotl** [comment]
didn't realize "add files via upload" would show, added a splash to show the controls

**Comment by Parker0808** [comment]
Looks like such a fun game!

**Comment by PossiblyAxolotl** [comment]
> Looks like such a fun game!
@Parker0808 

Thanks!

**Comment by jmtinycircuits** [comment]
Looks good!

**Pull request merged**
